	/*******************************************************************************/
	/* This script demonstrates queries for handling all the systems requirements  */
	/*******************************************************************************/


	/********************************************************************************/ 
	/*                 THIS BLOCK SETS UP THE DEMONSTRATION                         */
	/* SELECT AND EXECUTE ALL STATEMENTS DOWN TO THE BEGINNING OF THE DEMONSTRATION */
	/********************************************************************************/

USE HR_System;
/*1.	REF SR1.  FIND EMPLOYEE NAMES OF EMPLOYEES WITH TOP 5 SALARIES
		IN SALES DEPARTMENT? WHAT WERE THE INCENTIVES OFFERED? */


SELECT TOP(5) EMPLOYEES.EMPID,CONCAT(EMPLOYEES.FNAME,' ',EMPLOYEES.LNAME) AS NAME,(EMPLOYEES.BASIC_SAL+EMPLOYEES.INCENTIVES) AS TOTALSALARY 
FROM 
EMPLOYEES
INNER JOIN
DEPARTMENTS ON EMPLOYEES.DEPT_ID=DEPARTMENTS.DEPT_ID
WHERE 
DEPARTMENTS.DEPT_NAME='SALES'
ORDER BY TOTALSALARY DESC;


/*2.	REF SR2. LIST THE EMPLOYEES THAT PERFORM WELL AND WHAT WERE THEIR NAMES AND SCORES? */

SELECT TOP(5) CONCAT(FNAME,' ',LNAME) AS NAME,R.SCORE 
FROM REVIEWS R
INNER JOIN EMPLOYEES E 
ON R.EMPID=E.EMPID
WHERE R.SCORE > 3;

/*3.	REF SR3. HOW MANY EMPLOYEES ARE PERFORMING LOW IN SALES DEPARTMENT*/

SELECT * FROM REVIEWS R
INNER JOIN 
EMPLOYEES E ON R.EMPID=E.EMPID
WHERE DEPT_ID=(SELECT DEPT_ID FROM DEPARTMENTS WHERE DEPT_NAME='SALES')
AND R.SCORE<(SELECT MAX(SCORE) FROM REVIEWS);

/*4.	REF SR4.  FIND EMPLOYEES SKILLED IN JAVA WITH AN EXPERIENCE OF 
        5 YEARS AND HIGHER TO BE MOVED TO ANOTHER DEPARTMENT?*/

SELECT CONCAT(E.FNAME,E.LNAME) AS NAME,D.DEPT_NAME,S.SKILL_NAME,ES.EXPERIENCE
FROM SKILLS S
JOIN EMP_SKILLS ES
ON S.SKILL_ID=ES.SKILL_ID
JOIN EMPLOYEES E
ON E.EMPID=ES.EMPID
JOIN DEPARTMENTS D
ON E.DEPT_ID=D.DEPT_ID
WHERE SKILL_NAME='JAVA'
AND ES.EXPERIENCE>5;


/*5.	REF SR4. HOW WILL THE HR UPDATE THE SYSTEM WHEN A SUPERVISOR WILL COMMUNICATE 
        THAT AN EMPLOYEE IS MOVED TO A DIFFERENT DEPARTMENT? SORT BY DEPARTMENT IDENTIFIER */
		
SELECT * FROM EMPLOYEES WHERE STATUS='IN TRANSITION'
ORDER BY DEPT_ID;

/*6.	REF SR5. HOW MANY EMPLOYEES HAVE MORE THAN ONE SKILLS AND ARE EXPERIENCED IN THOSE SKILLS?*/

SELECT S.SKILL_NAME,ES.EXPERIENCE,E.EMPID
FROM EMP_SKILLS ES
JOIN EMPLOYEES E
ON E.EMPID=ES.EMPID
JOIN SKILLS S
ON ES.SKILL_ID=S.SKILL_ID
WHERE E.EMPID > (SELECT COUNT(EMPID) AS EMP FROM Emp_Skills S WHERE S.EMPID=ES.EMPID
				 HAVING COUNT(*)>1)
GROUP BY S.SKILL_NAME,ES.EXPERIENCE,E.EMPID




